// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6366ps4JUXGcyRNfgAokBX
// Component: KWGUqEZOm9
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_bentukcinta.module.css"; // plasmic-import: 6366ps4JUXGcyRNfgAokBX/projectcss
import sty from "./PlasmicTombolCinta.module.css"; // plasmic-import: KWGUqEZOm9/css

export type PlasmicTombolCinta__VariantMembers = {
  size: "small" | "large";
  type: "primary" | "secondary";
};

export type PlasmicTombolCinta__VariantsArgs = {
  size?: SingleChoiceArg<"small" | "large">;
  type?: SingleChoiceArg<"primary" | "secondary">;
};

type VariantPropType = keyof PlasmicTombolCinta__VariantsArgs;
export const PlasmicTombolCinta__VariantProps = new Array<VariantPropType>(
  "size",
  "type"
);

export type PlasmicTombolCinta__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTombolCinta__ArgsType;
export const PlasmicTombolCinta__ArgProps = new Array<ArgPropType>("children");

export type PlasmicTombolCinta__OverridesType = {
  root?: p.Flex<"button">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultTombolCintaProps {
  children?: React.ReactNode;
  size?: SingleChoiceArg<"small" | "large">;
  type?: SingleChoiceArg<"primary" | "secondary">;
  className?: string;
}

function PlasmicTombolCinta__RenderFunc(props: {
  variants: PlasmicTombolCinta__VariantsArgs;
  args: PlasmicTombolCinta__ArgsType;
  overrides: PlasmicTombolCinta__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    true ? (
      <button
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.button,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root,
          {
            [sty.rootsize_large]: hasVariant(variants, "size", "large"),
            [sty.rootsize_large_type_primary]:
              hasVariant(variants, "size", "large") &&
              hasVariant(variants, "type", "primary"),
            [sty.rootsize_small]: hasVariant(variants, "size", "small"),
            [sty.roottype_primary]: hasVariant(variants, "type", "primary"),
            [sty.roottype_secondary]: hasVariant(variants, "type", "secondary"),
            [sty.roottype_secondary_size_large]:
              hasVariant(variants, "size", "large") &&
              hasVariant(variants, "type", "secondary"),
            [sty.roottype_secondary_size_small]:
              hasVariant(variants, "size", "small") &&
              hasVariant(variants, "type", "secondary")
          }
        )}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Tombol Cinta",
            value: args.children,
            className: classNames(sty.slotTargetChildren, {
              [sty.slotTargetChildrensize_small]: hasVariant(
                variants,
                "size",
                "small"
              ),
              [sty.slotTargetChildrentype_secondary]: hasVariant(
                variants,
                "type",
                "secondary"
              )
            })
          })}
        </div>
      </button>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "button";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTombolCinta__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTombolCinta__VariantsArgs;
    args?: PlasmicTombolCinta__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTombolCinta__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTombolCinta__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTombolCinta__ArgProps,
          internalVariantPropNames: PlasmicTombolCinta__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTombolCinta__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTombolCinta";
  } else {
    func.displayName = `PlasmicTombolCinta.${nodeName}`;
  }
  return func;
}

export const PlasmicTombolCinta = Object.assign(
  // Top-level PlasmicTombolCinta renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicTombolCinta
    internalVariantProps: PlasmicTombolCinta__VariantProps,
    internalArgProps: PlasmicTombolCinta__ArgProps
  }
);

export default PlasmicTombolCinta;
/* prettier-ignore-end */
