// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6366ps4JUXGcyRNfgAokBX
// Component: lGTX7nAbs-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_bentukcinta.module.css"; // plasmic-import: 6366ps4JUXGcyRNfgAokBX/projectcss
import sty from "./PlasmicHeroDateTime.module.css"; // plasmic-import: lGTX7nAbs-/css

export type PlasmicHeroDateTime__VariantMembers = {};

export type PlasmicHeroDateTime__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeroDateTime__VariantsArgs;
export const PlasmicHeroDateTime__VariantProps = new Array<VariantPropType>();

export type PlasmicHeroDateTime__ArgsType = {
  month?: React.ReactNode;
  date?: React.ReactNode;
  year?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHeroDateTime__ArgsType;
export const PlasmicHeroDateTime__ArgProps = new Array<ArgPropType>(
  "month",
  "date",
  "year"
);

export type PlasmicHeroDateTime__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultHeroDateTimeProps {
  month?: React.ReactNode;
  date?: React.ReactNode;
  year?: React.ReactNode;
  className?: string;
}

function PlasmicHeroDateTime__RenderFunc(props: {
  variants: PlasmicHeroDateTime__VariantsArgs;
  args: PlasmicHeroDateTime__ArgsType;
  overrides: PlasmicHeroDateTime__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <span
        className={classNames(projectcss.all, projectcss.span, sty.span__g0FUl)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Month",
          value: args.month,
          className: classNames(sty.slotTargetMonth)
        })}
      </span>

      <span
        className={classNames(projectcss.all, projectcss.span, sty.span__pBk)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Date",
          value: args.date,
          className: classNames(sty.slotTargetDate)
        })}
      </span>

      <span
        className={classNames(projectcss.all, projectcss.span, sty.span__ps7KJ)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Year",
          value: args.year,
          className: classNames(sty.slotTargetYear)
        })}
      </span>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeroDateTime__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeroDateTime__VariantsArgs;
    args?: PlasmicHeroDateTime__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeroDateTime__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeroDateTime__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeroDateTime__ArgProps,
          internalVariantPropNames: PlasmicHeroDateTime__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHeroDateTime__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeroDateTime";
  } else {
    func.displayName = `PlasmicHeroDateTime.${nodeName}`;
  }
  return func;
}

export const PlasmicHeroDateTime = Object.assign(
  // Top-level PlasmicHeroDateTime renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHeroDateTime
    internalVariantProps: PlasmicHeroDateTime__VariantProps,
    internalArgProps: PlasmicHeroDateTime__ArgProps
  }
);

export default PlasmicHeroDateTime;
/* prettier-ignore-end */
